import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useEnableColoredMatchBg } from "@/hooks/useEnableColoredMatchBg";
import { useBlueWinTint } from "@/hooks/useBlueWinTint";
import { CyberToggle } from "@/components/cybertoggle";
import { SettingsCard } from "@/components/ui/settings-card";
export function ColoredMatchBgPreference() {
    const { enabled, setEnabled } = useEnableColoredMatchBg();
    const { enabled: blueWins, setEnabled: setBlueWins } = useBlueWinTint();
    return (_jsx(SettingsCard, { title: "Colored Match Background", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsx("div", { children: _jsx("span", { className: "text-flash/80 text-sm", children: "Tint match cards for wins and losses." }) }), _jsx(CyberToggle, { checked: enabled, onChange: (v) => setEnabled(v) })] }), enabled && (_jsxs(_Fragment, { children: [_jsx("div", { className: "mt-3 h-[1px] bg-gradient-to-r from-jade/10 via-flash/5 to-transparent" }), _jsxs("div", { className: "mt-2.5 flex items-center justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-[10px] font-mono tracking-[0.15em] uppercase text-flash/40", children: "Win color" }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: `w-3 h-3 rounded-[2px] transition-all ${!blueWins ? "ring-1 ring-jade/50 bg-jade/40" : "bg-jade/15"}` }), _jsx("span", { className: `text-[9px] font-mono tracking-wide ${!blueWins ? "text-jade/70" : "text-flash/25"}`, children: "GREEN" })] }), _jsx("span", { className: "text-flash/15 text-[8px]", children: "/" }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: `w-3 h-3 rounded-[2px] transition-all ${blueWins ? "ring-1 ring-[#5BA8E6]/50 bg-[#5BA8E6]/40" : "bg-[#5BA8E6]/15"}` }), _jsx("span", { className: `text-[9px] font-mono tracking-wide ${blueWins ? "text-[#5BA8E6]/70" : "text-flash/25"}`, children: "BLUE" })] })] }), _jsx(CyberToggle, { checked: blueWins, onChange: (v) => setBlueWins(v) })] })] }))] }) }));
}
